### ISSUE TITLE
Invert "from" label position

### ISSUE THREAD

**Issue by poweruser82** [jeena/Bungloo#196]
Put it to the bottom instead of top, so it doesn't partially cover the newer post you are going to read.

**Comment by poweruser82** [comment]
``` css

/* reverse app tab */
li .from {
    position: absolute;
    right: 10px;
    display: none;
    padding: 0.3em 0.9em;
    background: #ddd;
    font-size: 0.9em;

    top: auto;
    bottom: -1.8em;
    z-index: 2;
    -webkit-border-top-left-radius: 0;
    -webkit-border-top-right-radius: 0;
    -webkit-border-bottom-left-radius: 8px;
    -webkit-border-bottom-right-radius: 8px;
    -webkit-box-shadow: 0 2px 2px rgba(0, 0, 0, 0.1);
    border: 1px solid #b9b9b9;
    border-top: 0;
}

li:last-child:hover .from {
    top: -1.8em;
    bottom: auto;
    -webkit-border-top-left-radius: 8px;
    -webkit-border-top-right-radius: 8px;
    -webkit-border-bottom-left-radius: 0px;
    -webkit-border-bottom-right-radius: 0px;
    -webkit-box-shadow: 0 -2px 2px rgba(0, 0, 0, 0.1);
    border: 1px solid white;
    border-bottom: 0;
}
```

**Comment by jeena** [comment]
Can you make that a pull request instead?

**Comment by poweruser82** [comment]
I have no idea of how do it. I need a GitHub starter guide.
However I'm still testing it, I'm not that satisfied because it covers the time and buttons of previous post.

**Comment by poweruser82** [comment]
My current styling:

``` css
li .from {
    position: absolute;
    right: 4em;
    display: none;
    padding: 0.3em 0.9em;
    background: #ddd;
    font-size: 0.9em;

    top: auto;
    bottom: -1.8em;
    z-index: 2;
    -webkit-border-top-left-radius: 0;
    -webkit-border-top-right-radius: 0;
    -webkit-border-bottom-left-radius: 8px;
    -webkit-border-bottom-right-radius: 8px;
    -webkit-box-shadow: 0 2px 2px rgba(0, 0, 0, 0.1);
    border: 1px solid #b9b9b9;
    border-top: 0;
}

li:last-child:hover .from {
    top: -1.8em;
    bottom: auto;
    -webkit-border-top-left-radius: 8px;
    -webkit-border-top-right-radius: 8px;
    -webkit-border-bottom-left-radius: 0px;
    -webkit-border-bottom-right-radius: 0px;
    -webkit-box-shadow: 0 -2px 2px rgba(0, 0, 0, 0.1);
    border: 1px solid white;
    border-bottom: 0;
}
```
